services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: dev
      POSTGRES_USER: dev
      POSTGRES_DB: backups
    ports: ["5432:5432"]

  redis:
    image: redis:7
    command: ["redis-server","--requirepass", "devredis"]
    ports: ["6379:6379"]
